### ISSUE TITLE
Subsequent USB Transfers Fail

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [mrdude2478/Tinwoo-Release#2] opened 2024-11-19 17:21 UTC
emuMMC 19.0.1 / AMS1.8.0
Tinwoo v1.0.26
NS-USBloader v7.2
Sys-Patch 1.5.3

After a successful USB transfer has finished, trying to initiate a new USB transfer never starts and times out with message "Failed to install xxxx.nsp! Partially installed contents can be removed from the System Settings applet. BufferData:193: USB transfer timed out or failed"

The only way a new USB transfer can be done is by exiting Tinwoo and restarting it.

Don't know if this is a bug, or if a "Kill & Restart USB Connection" feature or something similar could be added.

**Comment by mrdude2478** [comment] 2024-11-25 17:49
I could probably add a check so that when the install queue reaches zero for usb it will disconnect. I'm pushing a new build out in a day or so that has block compression + new setting to disable tik warning. If I have some time I'll check this out at the same time. Thanks for reporting the issue.

**Comment by mrdude2478** [comment] 2024-11-26 01:37
Hi I've had a look at the error you reported, I can't get it to fail. When the usb install completes the program goes back to the main menu, then I just open up usb install again and on NS-USBLoader you just need to check the upload checkbox and then Upload to NS button again and it works fine. Did you check your USB cable is OK?

**Comment by harvestry-of-ghosts** [comment] 2024-11-26 02:45
I have tried several different USB C to A cables and they all provide the same result. Here is a video demonstrating with this cable, but like I said, all produced the same results:
https://www.amazon.com/gp/product/B07213D35X/

Video. Able to reproduce the failure of subsequent transfers 100% of the time:
https://youtu.be/tUcwHFvtkoM

**Comment by mrdude2478** [comment] 2024-11-26 03:33
Try this version of NS-Usbloader

https://mega.nz/file/I4p2gCCK#32GwAGtIcL3FVH-V-8Goae_hpnK8FQ0eS2PwLDOW6X4

Also grab the newest Tinwoo from the release page (1.0.27)

**Comment by harvestry-of-ghosts** [comment] 2024-11-26 05:13
Updated Tinwoo and used the provided NS-Usbloader. No change. Same behavior.

**Comment by mrdude2478** [comment] 2024-11-26 23:25
@harvestry-of-ghosts 

Thanks for posting the video, I've tried doing it the exact same way you are doing it but it still works fine for me with no problems. Are you able to try on a friends computer or a different computer with windows installed on it?

**Comment by harvestry-of-ghosts** [comment] 2024-11-27 13:57
Thanks for all of the advice thus far. I will try a different PC, using a 2.0 port (atmos is already set to use USB 3.0), and the code change if the other options do not remedy it. One question though, what do I change the code to?

From this:

void USBCmdManager::SendExitCmd()
	{
		USBCmdManager::SendCmdHeader(0, 0);
	}

To: ??? Just completely remove that portion, or?

**Comment by harvestry-of-ghosts** [comment] 2024-11-27 17:30
It is absolutely related to USB 3.0. it works fine on both my Desktop running W11 and laptop running Win10 using 2.0. Once I switch to 3.0 it fails as described in the issue. I've tried updating all of the USB 3.0 drivers for my PC, making sure power management on the ports was disabled (also tried enabled, and tried every combination of force USB 3.0 options in Atmos and Hekate ini's. Nothing made it work in 3.0.

So I guess if someone wants to compile the mentioned possible fix for it, I would be happy to test to see if it helps the USB 3.0 problem. Thanks again.

**Comment by mrdude2478** [comment] 2024-11-27 23:13
@harvestry-of-ghosts 

TBH I am pretty busy with work for now so It might take me a few days to make a test build for you if you don't know how to do it yourself. Just keep checking back now and again and when I get time I'll post a link in here when I get time.

**Comment by harvestry-of-ghosts** [comment] 2024-11-28 00:58
I've compiled things from different gits in the past but there were (imo) more precise instructions on how to install all of the prerequisites to do so. Thanks for your help. I'll check back now and then like you said. I really appreciate it and I'm sure many others running into problems when using USB 3.0 will also be thankful.

**Comment by impeeza** [comment] 2024-11-28 04:47
The instructions I use to build from Code:

I do use MinGW64, please extrapole commands for other O.S.

```
pacman -Syuu --noconfirm --needed git make devkit-env devkitA64 autoconf automake-wrapper switch-libzstd switch-libssh2 switch-zziplib switch-sdl2 switch-sdl2_ttf switch-sdl2_image switch-sdl2_gfx switch-sdl2_mixer switch-glad switch-glm switch-libdrm_nouveau switch-freetype switch-curl

cd ~
clone https://github.com/mrdude2478/TinWoo/  #THIS WAS THE SOURCE, YOU NEED TO PROVIDE YOUR SOURCE NOW
cd ~/TinWoo
#TinWoo require libusbhsfs from https://github.com/DarkMatterCore/libusbhsfs
#You need to build it manually, run commands:
cd ~/TinWoo/include/libusbhsfs/
make fs-libs -j$(nproc)
make BUILD_TYPE=GPL install -j$(nproc)
cd ~/TinWoo
make plutonium -j$(nproc)
make tinwoo -j$(nproc)
```

**Comment by harvestry-of-ghosts** [comment] 2024-11-28 15:13
@impeeza Thanks, but I'm lost. I tried to set up MinGW64 using both the Cygwin installer and the installer from https://github.com/niXman/mingw-builds-binaries. Any commands I try just say they aren't recognized so I'll just wait for yourself or mrdude to compile a version with the possible USB 3.0 fix.

**Comment by mrdude2478** [comment] 2024-11-28 20:28
@harvestry-of-ghosts 

Can you try this, I've commented out the line: tin::util::USBCmdManager::SendExitCmd();

This has been move to main menu exit command instead. So you will still go back to the main menu after your nsphas installed but the usb command won't be sent until you exit the app (which will cause a slight slowdown on exiting tinwoo).
[tinwoo.zip](https://github.com/user-attachments/files/17952140/tinwoo.zip)

I'm not sure if this will fix your problem, I tried it on my pc and it worked OK though.

**Comment by impeeza** [comment] 2024-11-28 21:03
> @impeeza Thanks, but I'm lost. I tried to set up MinGW64 using both the Cygwin installer and the installer from https://github.com/niXman/mingw-builds-binaries. Any commands I try just say they aren't recognized so I'll just wait for yourself or mrdude to compile a version with the possible USB 3.0 fix.

https://gbatemp.net/threads/setup-a-devkitpro-environment-on-windows.652238/

**Comment by harvestry-of-ghosts** [comment] 2024-11-28 22:54
@mrdude2478 

Test version works worse. The first transfer attempt doesn't even start now.

V2 report says 5 when using USB 3.0

**Comment by mrdude2478** [comment] 2024-11-28 22:57
> tin::util::USBCmdManager::SendExitCmd();

It should do, this code is only usually called after the install is completed, it shouldn't make any difference before the install starts. as for v2, it should say 5 that's correct.

**Comment by harvestry-of-ghosts** [comment] 2024-11-28 23:14
I went back and forth several times between the 1.0.27 release build and the test build. In all but a handful of times, the first transfer attempt failed when using the test build. I tried to reproduce what would make it work the few times it did but it seemed random. With the normal release there's never any issue with the first transfer at all. So perhaps something like a force kill & reconnect usb feature? Or a button combo that would do that? I dont know. Only that after many times swapping back and forth, V2 will barely ever work on even the first transfer.

If you don't even want to bother with it, that's fine too. I'll just exit Tinwoo and relaunch it for the times I would need this specific functionality. If you want to try to find the cause/solution, that's great. If not, it's not a huge issue.

**Comment by mrdude2478** [comment] 2024-11-28 23:41
Try this, the only change from the one in the release is this line:

//tin::util::USBCmdManager::SendExitCmd(); - all this does is send a usb to say the transfer is done, and it's sent after the install is completed.

Let me know the results.

[tinwoo(test).zip](https://github.com/user-attachments/files/17952887/tinwoo.test.zip)

**Comment by harvestry-of-ghosts** [comment] 2024-11-29 00:12
That one works great. No issues on first or subsequent transfers using USB 3.0. Thank you!

There is still a timeout problem on USB 3.0 as described in the topics you linked to. Too large of a queue or too large of a file will still time out on USB 3.0 but not 2.0. I noticed this installing Xenoblade Chronicles 3. It would give the timed out error right towards the end. Tried installing 3 times and same thing, right at the end. Switched to USB 2.0 and it installed completely on the first try. The subsequent transfer problem has been fixed so this issue can be closed. Just need to press the interrupt button on NS-USBLoader as you stated, which is far better than having to exit and restart Tinwoo.

Don't know what causes the time out only on USB 3.0 with a large queue or too large of a file though. Perhaps the libusbK drivers that get installed via NS-USBLoader are at fault for all of the USB 3.0 issues?

**Comment by mrdude2478** [comment] 2024-11-29 00:21
@harvestry-of-ghosts

The line comented out ony sends a command - USBCmdManager::SendCmdHeader(0, 0);

It should be doing anything with timing, the usb timout is currently - u64 timeout = 5000000000, I can increase this to double to time for you if you want to try that? but it's probably your pc usb port of cable that is causing the issues rather than software.

**Comment by harvestry-of-ghosts** [comment] 2024-11-29 01:05
I made a mistake in my last comment and was just coming to correct it. I was using the release version of Tinwoo on USB 3.0 when it was timing out with Xenoblade Chronicles 3 (13.79GB) & incorrectly stated that the timeout still occurs on the last test version. The last test version DOES fix both problems. Subsequent transfers and Xenoblade failed with USB 3.0 on 1.0.27 but both have no issues at all with the last test version. Reproduced 4 times so I consider #2 fixed. It most likely has also fixed the timeout problem several people were having with only USB 3.0.

**Comment by harvestry-of-ghosts** [comment] 2024-11-29 01:11
> @harvestry-of-ghosts
> 
> Here's the same as the one that worked for you but with double the usb write timeout.
> 
> [tinwoo(test timeout).zip](https://github.com/user-attachments/files/17953191/tinwoo.test.timeout.zip)

You got that one in while I was still typing my corrected info. lol. Probably not needed since Xenoblade was able to complete with the last test without the time increase. But at the same time I guess it wouldn't hurt anything to have it increased. So the increased time out version is 10000000000. What measurement? Microseconds, 2.77 hours?

**Comment by mrdude2478** [comment] 2024-11-29 01:29
I was looking that the main loop there - but all I can see that would cause usb issue is - socketInitializeDefault();, I think this is part of libnx rather than tinwoo. Anyway if your issue is now fixed I put the timeout back to the original value. I can add a setting in the settings page for USB 3 users like you that are having issues, for users that aren't having issues I can set this default value as off. I'll reopen this for now until I add that option.

**Comment by mrdude2478** [comment] 2024-11-29 02:06
@harvestry-of-ghosts 

I've re-enabled this ```tin::util::USBCmdManager::SendExitCmd();```

After the popup after install I added code to kill usb and then re-initialize it (so the computer will make a noise when usb is reconnected) when the main menu reloads.

Can you let me know if this is working for you?
[tinwoo(test3).zip](https://github.com/user-attachments/files/17953554/tinwoo.test3.zip)

**Comment by harvestry-of-ghosts** [comment] 2024-11-29 17:12
@mrdude2478 I will be testing this later today when I have some free time.

**Comment by harvestry-of-ghosts** [comment] 2024-12-02 12:24
So it works for the most part. It helps subsequent transfers work but there is still the seemingly random timing out and crashes over both USB 2.0 and 3.0. I kept getting time outs on long queues over USB 3.0 and switched to USB 2.0 to see if it would help that, but then I got an Atmosphere crash partway through the same queue.

Error Code: 2168 0002 0x4a8
Program: 010000000000100D

Which I believe is the Album. I was running Tinwoo via title override & not applet mode.

**Comment by harvestry-of-ghosts** [comment] 2024-12-02 18:16
I noticed something and not sure why I didn't look at the NS-USBloader log after a fail until now.

When Tinwoo gives me this message:

![IMG_20241202_115611296](https://github.com/user-attachments/assets/084e072e-2bf3-4e4a-911f-2ac21392eb11)

The log screen in NS-USBloader always gives this error (outlined in red):

![Clipboard_12-02-2024_01](https://github.com/user-attachments/assets/649551d3-bc49-4e3c-9ff6-1af202636554)

Thing is, there is 250 GB of free space on the sd card when this happens. Tinwoo and NS-USBloader give those same two messages every time a transfer fails. Don't know it that will help solve the random failures.

Also, don't know if you want a separate issue made for a feature request. If you look at first image, you notice how the file names get cut off in all Tinwoo screens if it's past a certain number of characters and will just have (...).nsp at end. Can you have it display the full title across two lines, or include a setting to enable/disable it?

**Comment by mrdude2478** [comment] 2024-12-02 18:55
@harvestry-of-ghosts 

Try renaming your nsp file to something short without the two sets of brackets.

**Comment by harvestry-of-ghosts** [comment] 2024-12-02 19:33
Yes, I know I could rename them all. I was asking for feature to list full title without having to rename. I have close to 200 nsps and the title format helps keep things organized. ;)

I just came across an error message I've never seen before after a failed transfer:

![IMG_20241202_132243428](https://github.com/user-attachments/assets/ec6a66a0-0724-485d-953e-10b24e72a024)

Retrying the same file was successful, so once again it all seems completely random.

**Comment by mrdude2478** [comment] 2024-12-02 20:47
@harvestry-of-ghosts 

I didn't ask you to rename all your NSP files, I wanted you to rename only one for to test the filename length. Still never mind. If your problem is random it could be down to a few things - SD card, sd card reader, usb cable, usb port etc. Did you try using a fresh sd card? Did you try using a nsp with a short name? etc.

Now as you already said, this works fine on different computers so I am going to assume you have a connection issue with your USB port, did you try using a USB hub or a different port etc....

**Comment by harvestry-of-ghosts** [comment] 2024-12-02 21:35
Nah, it's not my computer, or ports, or cable, or sd card, etc. These random failures only happen when using Awoo & Tinwoo, but not with DBI MTP, DBI + Backend, or TInfoil via USB. All using the same pc, ports, cables, and sd card. Since I began testing things, I noticed that the random failures with Awoo is well enough documented in several places to know that many others have the same problems. Shrug.

**Comment by mrdude2478** [comment] 2024-12-03 13:14
Maybe I can edit Tinwoo\source\util\usb_comms_tinleaf.c to report your USB connection as USB 2 instead of USB 3, If you have a look at the source impeeza linked you could probably do this by looking for - UsbDeviceSpeed_Super (usb3) and chaning that to  UsbDeviceSpeed_High (usb2). It's a pity you don't know how to compile stuff as this would be much faster to test, I'll have a look later today if I get some time.

**Comment by mrdude2478** [comment] 2024-12-04 00:11
@harvestry-of-ghosts, follow on from above post: Reported speeds in both AtmosphereNX and Tinwoo,

AtmosphereNX USB speed:
Vendor ID                : 0x057E (Nintendo Co., Ltd.)
Product ID               : 0x2000
Manufacturer String      : Nintendo
Product String           : Nintendo Switch
Serial                   : xxx
USB Version              : 2.0
Port maximum Speed       : High-Speed (Companion Port 3-2 is doing the SuperSpeed)
Device maximum Speed     : High-Speed
Device Connection Speed  : High-Speed
Self powered             : yes
Demanded Current         : 500 mA
Used Endpoints           : 2

Tinwoo Speed:
Vendor ID                : 0x057E (Nintendo Co., Ltd.)
Product ID               : 0x3000
Manufacturer String      : Nintendo
Product String           : Nintendo Switch
Serial                   : SerialNumber
USB Version              : 3.0
Port maximum Speed       : High-Speed (Companion Port 3-2 is doing the SuperSpeed)
Device maximum Speed     : SuperSpeed
Device Connection Speed  : High-Speed
Self powered             : yes
Demanded Current         : 500 mA
Used Endpoints           : 3

**Comment by harvestry-of-ghosts** [comment] 2024-12-04 19:49
Can you please explain what the change between x and z do?

**Comment by mrdude2478** [comment] 2024-12-05 01:40
The maximum filename length is 40 characters. Anything past that gets shortened to (...).nsp

**Comment by harvestry-of-ghosts** [comment] 2024-12-05 05:58
> The maximum filename length is 40 characters. Anything past that gets shortened to (...).nsp
> 
> That's only so it shows on the screen, it's not important to your issue. X version works fine on my switch and windows 10 using usb3 and I screen-shotted it so you could see that.
> 
> I can remove usb3 and force it to use all usb2 settings, that's the last thing I can do for you, after that I am out of ideas.

I know it's so it shows on the screen and that it's not relevant to this issue. That's why I asked if I should open it as a separate feature request.

Because X works fine on your Windows 10 & USB 3.0, doesn't mean it works on my Windows 11 7 USB 3.0. I've tried everything and every test build extensively and it always fails, randomly. It could fail on the first transfer in a queue, it could fail on the 10th transfer in a queue, the 20th, the 40th, etc. During your testing are you trying just one single file, or are you trying say 20-30 files with at least a few of them being 15+ GB titles? I can install 100+ files with DBI via MTP and have zero failures, where I can't do that with Tinwoo. Can't even do 10 transfer per queue and get through 2-3 queues without a failure somewhere along the way. Thing is, I can't get more than 30MB/s with DBI vs up to 60 with Tinwoo. That's why I don't just use DBI. It transfers at half the speed.

I don't even know what X and Z are even supposed to be accomplishing. X doesn't work for me. I tried it again and get the same message. it just disconnects and Windows doesn't even see the Switch.

![error 1](https://github.com/user-attachments/assets/0a00090b-758f-4ec4-bbeb-3bf15a66888d)

And then I've received this error a few times again. Although the code at the end is different. First one was 0x90d9c202, this one is 0xc8d9c402. I didn't catch what the code was the other couple times.

![error 2](https://github.com/user-attachments/assets/6d794ade-eb7f-4049-887e-74bd0ce28721)

What does all of that mean? The "InstallContentMetaRecords:66:....." part and error codes.

Not sure how much more testing I'm going to do. The two SD cards I've been using have been through the wringer and back with the tons and tons of writing from all of the testing. The only thing I can say is solved is the "Reinitialize USB connection after USB install" option does work very well. It's just the random failures that are still an issue for me when trying to do queues of 10-50 files. It will then randomly fail anywhere from the 1st to the 50th transfer. Again, no problems with over 100 transfer with DBI MTI Responder, so I don't think it's my PC, ports, cable, etc.

But yeah. I think I'm done testing. Thanks for adding the "Reinitialize USB connection after USB install" option (imo it should be included in the next release) & for trying to get the rest figured out. Judging from other peoples posts in several locations, the random failures are just that. Random. And no one has been able to figure out why they happen.

**Comment by mrdude2478** [comment] 2024-12-05 11:57
Random fails probably doesn't mean code issues in Tinwoo, it probably means something is messing with your USB connection and that's why you are getting the errors during writing and why you got the error writing data - InstallContentMetaRecord.

Now it could be down to your pc power settings, did you try disabling usb sleep - ![Power Settings](https://i.imgur.com/zBxoyef.png)

Also are you using any plugins on your switch, is your card exfat or fat32 - (fat32 works better), What are your sleep settings on your switch set to?

FYI if dbi is working for you, use that - some people reported slow usb speeds after version 527, maybe try using v526 and see if that solves your usb 3 speed issues. the current DBI only reports USB speed as 2.1 for me, maybe try having a look at this video to fix that - https://www.youtube.com/watch?v=SEvtKeoIqS8

**Comment by harvestry-of-ghosts** [comment] 2024-12-05 23:48
> In your screenshot it show your sd card only has over 8-9 gig of space, Hyrule Warriors Age of Calamity is larger than that at about 11.4 gig.......
> 

That is one of 2 SD cards I had been testing with. One is128GB and the other is a 515GB. I was using the 128GB card in that image. Base game and update were already installed. It failed on a small DLC file but you can't see that because of the character limit has the DLC titles cut off. ;)

> Random fails probably doesn't mean code issues in Tinwoo, it probably means something is messing with your USB connection and that's why you are getting the errors during writing and why you got the error writing data - InstallContentMetaRecord.
>

There I'm not sure why writing using other apps doesn't have the failures. To me that says it's something to do with one of, or any combination of Tinwoo, NS-USBloader, and libusbK. Not necessarily my PC or cables.

> Now it could be down to your pc power settings, did you try disabling usb sleep - ![Power Settings](https://camo.githubusercontent.com/c299524bdcfac60ef75c8c6f971281d535641d44bfe0520a340569ae03f7e04d/68747470733a2f2f692e696d6775722e636f6d2f7a42786f7965662e706e67)
> 

I mentioned pretty much early on that I had already done this. :)

> It could also be your antivirus app messing with ns-usbloader or some other software or setting on your computer. You could try using an ubuntu live cd/usb to see it this is causing an issue without needing to install anything or change anything on your computer.
> 

Only av I use is Windows Security and I have had it completely disabled during all testing. I also just did a compete fresh Windows install this morning to see if that would change anything but had the same results.

> Also are you using any plugins on your switch, is your card exfat or fat32 - (fat32 works better), What are your sleep settings on your switch set to?
> 

Sys-Patch and nx-ovlloader. Fat32. Switch is set to never sleep.

> FYI if dbi is working for you, use that (as i doesn't need ns-usbloader or java installed) - some people reported slow usb speeds after version 527, maybe try using v526 and see if that solves your usb 3 speed issues. the current DBI only reports USB speed as 2.1 for me, maybe try having a look at this video to fix that - https://www.youtube.com/watch?v=SEvtKeoIqS8
>

Nothing in that video about fixing slow USB 3.0 in DBI. They are using v358 and their transfers show 2.0 speeds. :P I've already tried 519 and 527. There is no 250-526. They're better, but still not as fast.

**Comment by mrdude2478** [comment] 2024-12-06 13:21
@harvestry-of-ghosts 

I'll close this issue now then as I can't reproduce the issues that you are having and I can't fix an intermittent fault that I am not getting. If I get a new laptop soon and it has usb 3.2 ports on it, I will try with that and see if I can reproduce the random errors you are getting.
In the meantime, you could try downloading and installing devkitpro and building from the source code @impeeza linked and try to fix yourself. If you come up with a solution you can post in here to say how you solved it.

**Closed by mrdude2478** 2024-12-06 13:21 UTC

**Comment by harvestry-of-ghosts** [comment] 2025-01-12 11:47
@mrdude2478 

From the dev of DBI:

"I can confirm that bug does exist. It is very very simple and can be easily fixed. Root cause is how app reads from usb, using libnx usb comms.

This is described on switchbrew.org site: when app reads some data from usb input buffer and that buffer has more data, than app reads that extra data is discarded. Inproper handling of this causes hangs or crashes. That's why this happened more on usb3: PC can push more data at the same time frame."

Perhaps that bit of info can help solve the crashing/time outs?

**Comment by harvestry-of-ghosts** [comment] 2025-01-14 15:28
Does this help any? Sorry, I have no idea what any of that means but I'm willing to test.

From: https://switchbrew.org/wiki/USB_services#PostBufferAsync

_PostBufferAsync
Takes an input u32 Size and an input u64 Buffer. Returns an output u32 UrbId.

The output urbId can then be used while parsing the output of #GetUrbReport, after waiting for the CompletionEvent to be signalled.

The buffer address must be 0x1000-byte aligned. The input size doesn't matter. It helps to use svcSetMemoryAttribute to turn off caching on the buffer.

Used for data-transfer with input/output endpoints.

The user-process must flush dcache for the buffer before using this command.

When sending data where size is larger than wMaxPacketSize, it will automatically send multiple USB packets where last packet size = {remaining size}. Every {wMaxPacketSize}-bytes is a different packet. This only occurs in some cases. When size is ~0x1000000(exact size unknown), Switch-side silently hangs, while host-side will timeout(no traffic on USB bus indicating failure).

For receiving data, if size is less than {actual received USB packet size} the rest of the packet will be discarded. Later PostBufferAsync cmd(s) will only return data from new packets, not the remainder of the earlier packet(s)._
